
export const metadata = {
  title: 'Blogs Page',
  description: 'Generated by create next app',
}

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        {children}      
    </>
  )
}
